site_name: Rodolfo_Aramayo
site_url: https://raramayo.github.io/Rodolfo_Aramayo/
nav:
    - Home: index.md
    - About me: 01_about_me.md
    - Research: 02_research.md
    - Teaching: 03_teaching.md
    - Publications: 04_publications.md
    - Funding: 05_funding.md
    - Resume: 06_Resume_Rodolfo_Aramayo.pdf
theme:
  name: 'material'
  # name: 'readthedocs'
  palette:
    - primary: 'black'
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - contents.tabs.link
    - content.code.annotation
    - content.code.copy
  plugins:
    - search:
    - social:
  lang: 'en'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/raramayo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rodolfo-aramayo-572297196/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - admonition:
  - pymdownx.arithmatex:
      generic: true
  - footnotes:
  - pymdownx.details:
  - pymdownx.superfences:
  - pymdownx.mark:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: |
  &copy; 2024 <a href+"https://github.com/raramayo" target="_b;ank" rel="noopener">Rodolfo Aramayo </a>
